### PR TITLE
Bump package versions

### PR DESCRIPTION
**Pull request by mschindlerMM**

### CODE REVIEW

**Review by Tranquility — COMMENTED** [review]
Two things come to mind:
1. I would prefer calling it javascript package instead of npm package.
2. They changes are pretty substantial and we should consider increasing the major version.

**Comment by mschindlerMM** [comment]
> Two things come to mind:
> 
> 1. I would prefer calling it javascript package instead of npm package.
> 2. They changes are pretty substantial and we should consider increasing the major version.

1.  Isn't it much easier to assume what package manager needs to be updated when naming it "NPM" instead of "JAVASCRIPT"?
2. We are just adding a new feature and not changing any existing feature. I would be fine increasing the minor version for NPM, but I don't think we need to increase the major version already

**Comment by Tranquility** [comment]
OK

**Comment by mschindlerMM** [comment]
@Tranquility changed it to a minor version now for the npm package

**Review by Tranquility — APPROVED** [review]

**Pull request merged**
